name: Hexo Deploy

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 12.x
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        submodules: true
    - name: Cache node modules
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
    # Deploy hexo blog website.
    - name: Deploy
      id: deploy
      env:
        TOEKN: ${{ github.token }}
      run: |
        npx hexo deploy
    # Use the output from the `deploy` step(use for test action)
    - name: Get the output
      run: |
        echo "${{ steps.deploy.outputs.notify }}"

