name: Hexo Deploy

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup ssh
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Clone repo
      run: |
        git clone --branch master git@github.com:YuGe/weiwei.git master
    - name: Install Dependencies
      run: |
        ls
        cd master
        git checkout master
        npm install
        npm audit fix
        npx hexo generate
        npx hexo deploy
